export const INVENTORY_RESERVE = 'INVENTORY_RESERVE';
export const INVENTORY_RESERVE_RESPONSE = 'INVENTORY_RESERVE_RESPONSE';
export const SHIPPING_VALIDATION = 'SHIPPING_VALIDATION';
export const SHIPPING_VALIDATION_RESPONSE = 'SHIPPING_VALIDATION_RESP';
export const INVENTORY_REMOVE = 'INVENTORY_REMOVE';
export const INVENTORY_REMOVE_RESPONSE = 'INVENTORY_REMOVE_RESP';
